apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-crawler-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: news.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: news-crawler-service
                port:
                  number: 8000