apiVersion: v1
kind: Service
metadata:
  name: news-crawler-service
spec:
  selector:
    app: news-crawler
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  type: ClusterIP